//----------------------------------------------------------------------------//
// Generated by LegUp High-Level Synthesis Tool Version 3.0 (http://legup.org)
// Compiled: Mon Jan 21 17:30:53 2013
// University of Toronto
// For research and academic purposes only. Commercial use is prohibited.
// Please send bugs to: legup@eecg.toronto.edu
// Date: Wed May 22 11:27:22 2013
//----------------------------------------------------------------------------//

`define MEMORY_CONTROLLER_ADDR_SIZE 32
`define MEMORY_CONTROLLER_DATA_SIZE 64
// Number of RAM elements: 2
`define MEMORY_CONTROLLER_TAG_SIZE 9
`define TAG_NULL `MEMORY_CONTROLLER_TAG_SIZE'd0
`define TAG_PROCESSOR `MEMORY_CONTROLLER_TAG_SIZE'd1
//   %a = alloca [2048 x i32], align 4
`define TAG_main_0_a `MEMORY_CONTROLLER_TAG_SIZE'd2
`define TAG_main_0_a_a {`TAG_main_0_a, 23'b0}
//   %b = alloca [2048 x i32], align 4
`define TAG_main_0_b `MEMORY_CONTROLLER_TAG_SIZE'd3
`define TAG_main_0_b_a {`TAG_main_0_b, 23'b0}

// Turn off warning 'ignoring unsupported system task'
// altera message_off 10175

module top
	(
		clk,
		reset,
		start,
		finish,
		return_val
	);
input clk;
input reset;
input start;
output wire finish;
output wire [31:0] return_val;
wire memory_controller_waitrequest;
wire memory_controller_enable_a;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
wire memory_controller_write_enable_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
wire [1:0] memory_controller_size_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;

wire memory_controller_enable_b;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
wire memory_controller_write_enable_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
wire [1:0] memory_controller_size_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;

assign memory_controller_waitrequest = 0;

memory_controller memory_controller_inst (
	.clk( clk ),
	.memory_controller_enable_a( memory_controller_enable_a ),
	.memory_controller_enable_b( memory_controller_enable_b ),
	.memory_controller_address_a( memory_controller_address_a ),
	.memory_controller_address_b( memory_controller_address_b ),
	.memory_controller_write_enable_a( memory_controller_write_enable_a ),
	.memory_controller_write_enable_b( memory_controller_write_enable_b ),
	.memory_controller_in_a( memory_controller_in_a ),
	.memory_controller_in_b( memory_controller_in_b ),
	.memory_controller_size_a( memory_controller_size_a ),
	.memory_controller_size_b( memory_controller_size_b ),
	.memory_controller_waitrequest( memory_controller_waitrequest ),
	.memory_controller_out_reg_a( memory_controller_out_a ),
	.memory_controller_out_reg_b( memory_controller_out_b )
);

main main_inst(
	.clk( clk ),
	.clk2x( clk2x ),
	.clk1x_follower( clk1x_follower ),
	.reset( reset ),
	.start( start ),
	.finish( finish ),
	.return_val( return_val ),
	.memory_controller_address_a( memory_controller_address_a ),
	.memory_controller_address_b( memory_controller_address_b ),
	.memory_controller_enable_a( memory_controller_enable_a ),
	.memory_controller_enable_b( memory_controller_enable_b ),
	.memory_controller_write_enable_a( memory_controller_write_enable_a ),
	.memory_controller_write_enable_b( memory_controller_write_enable_b ),
	.memory_controller_waitrequest( memory_controller_waitrequest ),
	.memory_controller_in_a( memory_controller_in_a ),
	.memory_controller_in_b( memory_controller_in_b ),
	.memory_controller_size_a( memory_controller_size_a ),
	.memory_controller_size_b( memory_controller_size_b ),
	.memory_controller_out_a( memory_controller_out_a ),
	.memory_controller_out_b( memory_controller_out_b )
);

endmodule
`timescale 1 ns / 1 ns
module memory_controller
(
	clk,
	memory_controller_address_a,
	memory_controller_address_b,
	memory_controller_enable_a,
	memory_controller_enable_b,
	memory_controller_write_enable_a,
	memory_controller_write_enable_b,
	memory_controller_in_a,
	memory_controller_in_b,
	memory_controller_size_a,
	memory_controller_size_b,
	memory_controller_waitrequest,
	memory_controller_out_reg_a,
	memory_controller_out_reg_b
);


input clk;
input memory_controller_waitrequest;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
input memory_controller_enable_a;
input memory_controller_write_enable_a;
input [64-1:0] memory_controller_in_a;
input [1:0] memory_controller_size_a;
output reg [64-1:0] memory_controller_out_reg_a;
reg [64-1:0] memory_controller_out_prev_a;
reg [64-1:0] memory_controller_out_a;

reg memory_controller_enable_reg_a;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
input memory_controller_enable_b;
input memory_controller_write_enable_b;
input [64-1:0] memory_controller_in_b;
input [1:0] memory_controller_size_b;
output reg [64-1:0] memory_controller_out_reg_b;
reg [64-1:0] memory_controller_out_prev_b;
reg [64-1:0] memory_controller_out_b;

reg memory_controller_enable_reg_b;

reg [10:0] main_0_a_address_a;
reg [10:0] main_0_a_address_b;
reg main_0_a_write_enable_a;
reg main_0_a_write_enable_b;
reg [31:0] main_0_a_in_a;
reg [31:0] main_0_a_in_b;
wire [31:0] main_0_a_out_a;
wire [31:0] main_0_a_out_b;

//   %a = alloca [2048 x i32], align 4
ram_dual_port main_0_a (
	.clk( clk ),
	.address_a( main_0_a_address_a ),
	.address_b( main_0_a_address_b ),
	.wren_a( main_0_a_write_enable_a ),
	.wren_b( main_0_a_write_enable_b ),
	.data_a( main_0_a_in_a ),
	.data_b( main_0_a_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( main_0_a_out_a ),
	.q_b( main_0_a_out_b)
);
defparam main_0_a.width_a = 32;
defparam main_0_a.width_b = 32;
defparam main_0_a.widthad_a = 11;
defparam main_0_a.widthad_b = 11;
defparam main_0_a.width_be_a = 1;
defparam main_0_a.width_be_b = 1;
defparam main_0_a.numwords_a = 2048;
defparam main_0_a.numwords_b = 2048;


reg [10:0] main_0_b_address_a;
reg [10:0] main_0_b_address_b;
reg main_0_b_write_enable_a;
reg main_0_b_write_enable_b;
reg [31:0] main_0_b_in_a;
reg [31:0] main_0_b_in_b;
wire [31:0] main_0_b_out_a;
wire [31:0] main_0_b_out_b;

//   %b = alloca [2048 x i32], align 4
ram_dual_port main_0_b (
	.clk( clk ),
	.address_a( main_0_b_address_a ),
	.address_b( main_0_b_address_b ),
	.wren_a( main_0_b_write_enable_a ),
	.wren_b( main_0_b_write_enable_b ),
	.data_a( main_0_b_in_a ),
	.data_b( main_0_b_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( main_0_b_out_a ),
	.q_b( main_0_b_out_b)
);
defparam main_0_b.width_a = 32;
defparam main_0_b.width_b = 32;
defparam main_0_b.widthad_a = 11;
defparam main_0_b.widthad_b = 11;
defparam main_0_b.width_be_a = 1;
defparam main_0_b.width_be_b = 1;
defparam main_0_b.numwords_a = 2048;
defparam main_0_b.numwords_b = 2048;

wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_a;
assign tag_a = memory_controller_address_a[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_a;
reg [1:0] prevSize_a;
reg [2:0] prevSize_a_and;

always @(posedge clk)
begin
	prevAddr_a <= memory_controller_address_a[2:0];
	prevSize_a <= memory_controller_size_a;
end
wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_b;
assign tag_b = memory_controller_address_b[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_b;
reg [1:0] prevSize_b;
reg [2:0] prevSize_b_and;

always @(posedge clk)
begin
	prevAddr_b <= memory_controller_address_b[2:0];
	prevSize_b <= memory_controller_size_b;
end

reg [2:0] select_not_struct_a;

wire select_main_0_a_a;
assign select_main_0_a_a = (tag_a ==`TAG_main_0_a);
reg select_main_0_a_reg_a;
wire [31:0] memory_controller_main_0_a_out_a;
assign memory_controller_main_0_a_out_a = {32{ select_main_0_a_reg_a}} & main_0_a_out_a;

wire select_main_0_b_a;
assign select_main_0_b_a = (tag_a ==`TAG_main_0_b);
reg select_main_0_b_reg_a;
wire [31:0] memory_controller_main_0_b_out_a;
assign memory_controller_main_0_b_out_a = {32{ select_main_0_b_reg_a}} & main_0_b_out_a;

always @(*)
begin
	main_0_a_address_a = memory_controller_address_a [11-1+2:2] & {11{select_main_0_a_a}};
	main_0_a_write_enable_a = memory_controller_write_enable_a & select_main_0_a_a;
	main_0_a_in_a [32-1:0] = memory_controller_in_a[32-1:0];

	main_0_b_address_a = memory_controller_address_a [11-1+2:2] & {11{select_main_0_b_a}};
	main_0_b_write_enable_a = memory_controller_write_enable_a & select_main_0_b_a;
	main_0_b_in_a [32-1:0] = memory_controller_in_a[32-1:0];

end
always @(*)
begin
	select_not_struct_a [2:0] = 3'b0 | {2{select_main_0_a_reg_a}} | {2{select_main_0_b_reg_a}};
	if (prevAddr_a[2:0] & select_not_struct_a[2:0] != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_a_and[0] = prevSize_a[1] | prevSize_a[0];
	prevSize_a_and[1] = prevSize_a[1];
	prevSize_a_and[2] = prevSize_a[1] & prevSize_a[0];
	if ((prevAddr_a & prevSize_a_and) != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram size!");
		$finish;
	end
	memory_controller_out_prev_a = memory_controller_out_reg_a & { 64{!memory_controller_enable_reg_a}};
	memory_controller_out_a = 1'b0 | memory_controller_out_prev_a | memory_controller_main_0_a_out_a | memory_controller_main_0_b_out_a;
end

always @(posedge clk)
begin
memory_controller_out_reg_a <= memory_controller_out_a;
memory_controller_enable_reg_a <= memory_controller_enable_a;
select_main_0_a_reg_a <= select_main_0_a_a;
select_main_0_b_reg_a <= select_main_0_b_a;
end

reg [2:0] select_not_struct_b;

wire select_main_0_a_b;
assign select_main_0_a_b = (tag_b ==`TAG_main_0_a);
reg select_main_0_a_reg_b;
wire [31:0] memory_controller_main_0_a_out_b;
assign memory_controller_main_0_a_out_b = {32{ select_main_0_a_reg_b}} & main_0_a_out_b;

wire select_main_0_b_b;
assign select_main_0_b_b = (tag_b ==`TAG_main_0_b);
reg select_main_0_b_reg_b;
wire [31:0] memory_controller_main_0_b_out_b;
assign memory_controller_main_0_b_out_b = {32{ select_main_0_b_reg_b}} & main_0_b_out_b;

always @(*)
begin
	main_0_a_address_b = memory_controller_address_b [11-1+2:2] & {11{select_main_0_a_b}};
	main_0_a_write_enable_b = memory_controller_write_enable_b & select_main_0_a_b;
	main_0_a_in_b [32-1:0] = memory_controller_in_b[32-1:0];

	main_0_b_address_b = memory_controller_address_b [11-1+2:2] & {11{select_main_0_b_b}};
	main_0_b_write_enable_b = memory_controller_write_enable_b & select_main_0_b_b;
	main_0_b_in_b [32-1:0] = memory_controller_in_b[32-1:0];

end
always @(*)
begin
	select_not_struct_b [2:0] = 3'b0 | {2{select_main_0_a_reg_b}} | {2{select_main_0_b_reg_b}};
	if (prevAddr_b[2:0] & select_not_struct_b[2:0] != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_b_and[0] = prevSize_b[1] | prevSize_b[0];
	prevSize_b_and[1] = prevSize_b[1];
	prevSize_b_and[2] = prevSize_b[1] & prevSize_b[0];
	if ((prevAddr_b & prevSize_b_and) != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram size!");
		$finish;
	end
	memory_controller_out_prev_b = memory_controller_out_reg_b & { 64{!memory_controller_enable_reg_b}};
	memory_controller_out_b = 1'b0 | memory_controller_out_prev_b | memory_controller_main_0_a_out_b | memory_controller_main_0_b_out_b;
end

always @(posedge clk)
begin
memory_controller_out_reg_b <= memory_controller_out_b;
memory_controller_enable_reg_b <= memory_controller_enable_b;
select_main_0_a_reg_b <= select_main_0_a_b;
select_main_0_b_reg_b <= select_main_0_b_b;
end

endmodule 
`timescale 1 ns / 1 ns
module main
(
	clk,
	clk2x,
	clk1x_follower,
	reset,
	start,
	finish,
	return_val,
	memory_controller_enable_a,
	memory_controller_address_a,
	memory_controller_write_enable_a,
	memory_controller_in_a,
	memory_controller_size_a,
	memory_controller_out_a,
	memory_controller_enable_b,
	memory_controller_address_b,
	memory_controller_write_enable_b,
	memory_controller_in_b,
	memory_controller_size_b,
	memory_controller_out_b,
	memory_controller_waitrequest
);

parameter [3:0] LEGUP_0 = 4'd0;
parameter [3:0] LEGUP_F_main_BB_0_1 = 4'd1;
parameter [3:0] LEGUP_F_main_BB_1_2 = 4'd2;
parameter [3:0] LEGUP_F_main_BB_4_3 = 4'd3;
parameter [3:0] LEGUP_F_main_BB_legup_memset_4_exit_4 = 4'd4;
parameter [3:0] LEGUP_F_main_BB_legup_memset_4_exit_5 = 4'd5;
parameter [3:0] LEGUP_F_main_BB_9_6 = 4'd6;
parameter [3:0] LEGUP_F_main_BB_12_7 = 4'd7;
parameter [3:0] LEGUP_F_main_BB_legup_memset_4_exit3_8 = 4'd8;
parameter [3:0] LEGUP_F_main_BB_legup_memset_4_exit3_9 = 4'd9;
parameter [3:0] LEGUP_F_main_BB_17_10 = 4'd10;
parameter [3:0] LEGUP_F_main_BB___crit_edge_11 = 4'd11;
parameter [3:0] LEGUP_F_main_BB___crit_edge_12 = 4'd12;
parameter [3:0] LEGUP_F_main_BB___crit_edge_13 = 4'd13;
parameter [3:0] LEGUP_F_main_BB_22_14 = 4'd14;

input  clk;
input  clk2x;
input  clk1x_follower;
input  reset;
input  start;
output reg  finish;
output reg [31:0] return_val;
output reg  memory_controller_enable_a;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
output reg  memory_controller_write_enable_a;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
output reg [1:0] memory_controller_size_a;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;
output reg  memory_controller_enable_b;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
output reg  memory_controller_write_enable_b;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
output reg [1:0] memory_controller_size_b;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;
input  memory_controller_waitrequest;
reg [3:0] cur_state;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_0_tmp;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_0_tmp_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_1_s_i_0;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_1_s_i_0_reg;
reg [31:0] main_1_2;
reg [31:0] main_1_2_reg;
reg  main_1_3;
reg [31:0] main_4_5;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_4_6;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit_7;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit_8;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit_8_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit_tmp1;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit_tmp1_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_9_s_i2_0;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_9_s_i2_0_reg;
reg [31:0] main_9_10;
reg [31:0] main_9_10_reg;
reg  main_9_11;
reg [31:0] main_12_13;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_12_14;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit3_15;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit3_16;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_legup_memset_4_exit3_16_reg;
reg [31:0] main_17_18;
reg [31:0] main_17_19;
reg [31:0] main_17_sum_02;
reg [31:0] main_17_i_01;
reg [31:0] main_17_i_01_reg;
reg [31:0] main_17_20;
reg [31:0] main_17_21;
reg [31:0] main_17_21_reg;
reg  main_17_exitcond;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main___crit_edge_scevgep_phi_trans_insert;
reg [31:0] main___crit_edge__pre;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main___crit_edge_scevgep3_phi_trans_insert;
reg [31:0] main___crit_edge__pre4;
reg [31:0] main___crit_edge_phitmp;
reg [31:0] main___crit_edge_phitmp_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_1_s_i_0_phi_temp;
reg [31:0] main_1_2_phi_temp;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_9_s_i2_0_phi_temp;
reg [31:0] main_9_10_phi_temp;
reg [31:0] main_17_18_phi_temp;
reg [31:0] main_17_19_phi_temp;
reg [31:0] main_17_sum_02_phi_temp;
reg [31:0] main_17_i_01_phi_temp;


always @(posedge clk) begin
if (((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_0;
if (^reset !== 1'bX && ^(LEGUP_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_0_1;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_0_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd0)))
begin
cur_state <= LEGUP_0;
if (^reset !== 1'bX && ^(LEGUP_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_0_1) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_0_1;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_0_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_0_1) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_1_2;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_1_2) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_1_2;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_1_2) & (memory_controller_waitrequest == 1'd0)) & (main_1_3 == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit_4;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit_4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_1_2) & (memory_controller_waitrequest == 1'd0)) & (main_1_3 == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_4_3;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_4_3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_4_3) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_4_3;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_4_3) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_4_3) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_1_2;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit_4;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit_4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit_5;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit_5;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_9_6;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_9_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_9_6) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_9_6;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_9_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_9_6) & (memory_controller_waitrequest == 1'd0)) & (main_9_11 == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit3_8;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit3_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_9_6) & (memory_controller_waitrequest == 1'd0)) & (main_9_11 == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_12_7;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_12_7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_12_7) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_12_7;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_12_7) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_12_7) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_9_6;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_9_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit3_8;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit3_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit3_9;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit3_9) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_legup_memset_4_exit3_9;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_legup_memset_4_exit3_9) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_17_10;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_17_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_17_10) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_17_10;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_17_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_17_10) & (memory_controller_waitrequest == 1'd0)) & (main_17_exitcond == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_22_14;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_22_14) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((((cur_state == LEGUP_F_main_BB_17_10) & (memory_controller_waitrequest == 1'd0)) & (main_17_exitcond == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_11;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_11) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_11;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_11) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_11) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_12;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_12) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_12) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_12;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_12) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_12) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_13;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_13) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB___crit_edge_13;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB___crit_edge_13) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_F_main_BB_17_10;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_17_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_22_14) & (memory_controller_waitrequest == 1'd1)))
begin
cur_state <= LEGUP_F_main_BB_22_14;
if (^reset !== 1'bX && ^(LEGUP_F_main_BB_22_14) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if (((cur_state == LEGUP_F_main_BB_22_14) & (memory_controller_waitrequest == 1'd0)))
begin
cur_state <= LEGUP_0;
if (^reset !== 1'bX && ^(LEGUP_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
if ((reset == 1'd1))
begin
cur_state <= 4'd0;
if (^reset !== 1'bX && ^(4'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cur_state"); $finish; end
end
end
always @(*) begin
/* main: %0*/
/*   %tmp = getelementptr inbounds [2048 x i32]* %a, i32 0, i32 0*/
if (reset) begin main_0_tmp = 0; end
begin
main_0_tmp = `TAG_main_0_a_a;
end
end
always @(posedge clk) begin
/* main: %0*/
/*   %tmp = getelementptr inbounds [2048 x i32]* %a, i32 0, i32 0*/
if ((cur_state == LEGUP_F_main_BB_0_1))
begin
main_0_tmp_reg <= main_0_tmp;
if (^reset !== 1'bX && ^(main_0_tmp) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_0_tmp_reg"); $finish; end
end
end
always @(*) begin
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0 = main_1_s_i_0_phi_temp;
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
else if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0 = main_1_s_i_0_phi_temp;
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
else /* if ((cur_state == LEGUP_F_main_BB_1_2)) */
begin
main_1_s_i_0 = main_1_s_i_0_phi_temp;
end
end
always @(posedge clk) begin
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0_reg <= main_1_s_i_0;
if (^reset !== 1'bX && ^(main_1_s_i_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_reg"); $finish; end
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0_reg <= main_1_s_i_0;
if (^reset !== 1'bX && ^(main_1_s_i_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_reg"); $finish; end
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0_reg <= main_1_s_i_0;
if (^reset !== 1'bX && ^(main_1_s_i_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_reg"); $finish; end
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_s_i_0_reg <= main_1_s_i_0;
if (^reset !== 1'bX && ^(main_1_s_i_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_reg"); $finish; end
end
end
always @(*) begin
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_2 = main_1_2_phi_temp;
end
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
else /* if ((cur_state == LEGUP_F_main_BB_1_2)) */
begin
main_1_2 = main_1_2_phi_temp;
end
end
always @(posedge clk) begin
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_2_reg <= main_1_2;
if (^reset !== 1'bX && ^(main_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_2_reg"); $finish; end
end
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_2_reg <= main_1_2;
if (^reset !== 1'bX && ^(main_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_2_reg"); $finish; end
end
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if ((cur_state == LEGUP_F_main_BB_1_2))
begin
main_1_2_reg <= main_1_2;
if (^reset !== 1'bX && ^(main_1_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_2_reg"); $finish; end
end
end
always @(*) begin
/* main: %1*/
/*   %3 = icmp eq i32 %2, 0*/
begin
main_1_3 = (main_1_2 == 32'd0);
end
end
always @(*) begin
/* main: %4*/
/*   %5 = add i32 %2, -1*/
begin
main_4_5 = (main_1_2_reg + -32'd1);
end
end
always @(*) begin
/* main: %4*/
/*   %6 = getelementptr inbounds i32* %s.i.0, i32 1*/
begin
main_4_6 = (main_1_s_i_0_reg + (4 * 32'd1));
end
end
always @(*) begin
/* main: %legup_memset_4.exit*/
/*   %7 = getelementptr [2048 x i32]* %a, i32 0, i32 1*/
if (reset) begin main_legup_memset_4_exit_7 = 0; end
begin
main_legup_memset_4_exit_7 = (`TAG_main_0_a_a + (4 * 32'd1));
end
end
always @(*) begin
/* main: %legup_memset_4.exit*/
/*   %8 = getelementptr [2048 x i32]* %a, i32 0, i32 2*/
if (reset) begin main_legup_memset_4_exit_8 = 0; end
begin
main_legup_memset_4_exit_8 = (`TAG_main_0_a_a + (4 * 32'd2));
end
end
always @(posedge clk) begin
/* main: %legup_memset_4.exit*/
/*   %8 = getelementptr [2048 x i32]* %a, i32 0, i32 2*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
main_legup_memset_4_exit_8_reg <= main_legup_memset_4_exit_8;
if (^reset !== 1'bX && ^(main_legup_memset_4_exit_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_legup_memset_4_exit_8_reg"); $finish; end
end
end
always @(*) begin
/* main: %legup_memset_4.exit*/
/*   %tmp1 = getelementptr inbounds [2048 x i32]* %b, i32 0, i32 0*/
if (reset) begin main_legup_memset_4_exit_tmp1 = 0; end
begin
main_legup_memset_4_exit_tmp1 = `TAG_main_0_b_a;
end
end
always @(posedge clk) begin
/* main: %legup_memset_4.exit*/
/*   %tmp1 = getelementptr inbounds [2048 x i32]* %b, i32 0, i32 0*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
main_legup_memset_4_exit_tmp1_reg <= main_legup_memset_4_exit_tmp1;
if (^reset !== 1'bX && ^(main_legup_memset_4_exit_tmp1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_legup_memset_4_exit_tmp1_reg"); $finish; end
end
end
always @(*) begin
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0 = main_9_s_i2_0_phi_temp;
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
else if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0 = main_9_s_i2_0_phi_temp;
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
else /* if ((cur_state == LEGUP_F_main_BB_9_6)) */
begin
main_9_s_i2_0 = main_9_s_i2_0_phi_temp;
end
end
always @(posedge clk) begin
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0_reg <= main_9_s_i2_0;
if (^reset !== 1'bX && ^(main_9_s_i2_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_reg"); $finish; end
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0_reg <= main_9_s_i2_0;
if (^reset !== 1'bX && ^(main_9_s_i2_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_reg"); $finish; end
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0_reg <= main_9_s_i2_0;
if (^reset !== 1'bX && ^(main_9_s_i2_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_reg"); $finish; end
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_s_i2_0_reg <= main_9_s_i2_0;
if (^reset !== 1'bX && ^(main_9_s_i2_0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_reg"); $finish; end
end
end
always @(*) begin
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_10 = main_9_10_phi_temp;
end
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
else /* if ((cur_state == LEGUP_F_main_BB_9_6)) */
begin
main_9_10 = main_9_10_phi_temp;
end
end
always @(posedge clk) begin
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_10_reg <= main_9_10;
if (^reset !== 1'bX && ^(main_9_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_10_reg"); $finish; end
end
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_10_reg <= main_9_10;
if (^reset !== 1'bX && ^(main_9_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_10_reg"); $finish; end
end
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if ((cur_state == LEGUP_F_main_BB_9_6))
begin
main_9_10_reg <= main_9_10;
if (^reset !== 1'bX && ^(main_9_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_10_reg"); $finish; end
end
end
always @(*) begin
/* main: %9*/
/*   %11 = icmp eq i32 %10, 0*/
begin
main_9_11 = (main_9_10 == 32'd0);
end
end
always @(*) begin
/* main: %12*/
/*   %13 = add i32 %10, -1*/
begin
main_12_13 = (main_9_10_reg + -32'd1);
end
end
always @(*) begin
/* main: %12*/
/*   %14 = getelementptr inbounds i32* %s.i2.0, i32 1*/
begin
main_12_14 = (main_9_s_i2_0_reg + (4 * 32'd1));
end
end
always @(*) begin
/* main: %legup_memset_4.exit3*/
/*   %15 = getelementptr [2048 x i32]* %b, i32 0, i32 1*/
if (reset) begin main_legup_memset_4_exit3_15 = 0; end
begin
main_legup_memset_4_exit3_15 = (`TAG_main_0_b_a + (4 * 32'd1));
end
end
always @(*) begin
/* main: %legup_memset_4.exit3*/
/*   %16 = getelementptr [2048 x i32]* %b, i32 0, i32 2*/
if (reset) begin main_legup_memset_4_exit3_16 = 0; end
begin
main_legup_memset_4_exit3_16 = (`TAG_main_0_b_a + (4 * 32'd2));
end
end
always @(posedge clk) begin
/* main: %legup_memset_4.exit3*/
/*   %16 = getelementptr [2048 x i32]* %b, i32 0, i32 2*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
main_legup_memset_4_exit3_16_reg <= main_legup_memset_4_exit3_16;
if (^reset !== 1'bX && ^(main_legup_memset_4_exit3_16) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_legup_memset_4_exit3_16_reg"); $finish; end
end
end
always @(*) begin
/* main: %17*/
/*   %18 = phi i32 [ 4, %legup_memset_4.exit3 ], [ %.pre4, %._crit_edge ]*/
begin
main_17_18 = main_17_18_phi_temp;
end
end
always @(*) begin
/* main: %17*/
/*   %19 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %.pre, %._crit_edge ]*/
begin
main_17_19 = main_17_19_phi_temp;
end
end
always @(*) begin
/* main: %17*/
/*   %sum.02 = phi i32 [ 0, %legup_memset_4.exit3 ], [ %21, %._crit_edge ]*/
begin
main_17_sum_02 = main_17_sum_02_phi_temp;
end
end
always @(*) begin
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01 = main_17_i_01_phi_temp;
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
else if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01 = main_17_i_01_phi_temp;
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
else if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01 = main_17_i_01_phi_temp;
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
else /* if ((cur_state == LEGUP_F_main_BB_17_10)) */
begin
main_17_i_01 = main_17_i_01_phi_temp;
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01_reg <= main_17_i_01;
if (^reset !== 1'bX && ^(main_17_i_01) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_reg"); $finish; end
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01_reg <= main_17_i_01;
if (^reset !== 1'bX && ^(main_17_i_01) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_reg"); $finish; end
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01_reg <= main_17_i_01;
if (^reset !== 1'bX && ^(main_17_i_01) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_reg"); $finish; end
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01_reg <= main_17_i_01;
if (^reset !== 1'bX && ^(main_17_i_01) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_reg"); $finish; end
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_i_01_reg <= main_17_i_01;
if (^reset !== 1'bX && ^(main_17_i_01) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_reg"); $finish; end
end
end
always @(*) begin
/* main: %17*/
/*   %20 = mul nsw i32 %18, %19*/
begin
main_17_20 = (main_17_18 * main_17_19);
end
end
always @(*) begin
/* main: %17*/
/*   %21 = add nsw i32 %20, %sum.02*/
begin
main_17_21 = (main_17_20 + main_17_sum_02);
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %21 = add nsw i32 %20, %sum.02*/
if ((cur_state == LEGUP_F_main_BB_17_10))
begin
main_17_21_reg <= main_17_21;
if (^reset !== 1'bX && ^(main_17_21) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_21_reg"); $finish; end
end
end
always @(*) begin
/* main: %17*/
/*   %exitcond = icmp eq i32 %i.01, 2048*/
begin
main_17_exitcond = (main_17_i_01 == 32'd2048);
end
end
always @(*) begin
/* main: %._crit_edge*/
/*   %scevgep.phi.trans.insert = getelementptr [2048 x i32]* %a, i32 0, i32 %i.01*/
begin
main___crit_edge_scevgep_phi_trans_insert = (`TAG_main_0_a_a + (4 * main_17_i_01_reg));
end
end
always @(*) begin
/* main: %._crit_edge*/
/*   %.pre = load i32* %scevgep.phi.trans.insert, align 4, !tbaa !0*/
begin
main___crit_edge__pre = memory_controller_out_a[31:0];
end
end
always @(*) begin
/* main: %._crit_edge*/
/*   %scevgep3.phi.trans.insert = getelementptr [2048 x i32]* %b, i32 0, i32 %i.01*/
begin
main___crit_edge_scevgep3_phi_trans_insert = (`TAG_main_0_b_a + (4 * main_17_i_01_reg));
end
end
always @(*) begin
/* main: %._crit_edge*/
/*   %.pre4 = load i32* %scevgep3.phi.trans.insert, align 4, !tbaa !0*/
begin
main___crit_edge__pre4 = memory_controller_out_b[31:0];
end
end
always @(*) begin
/* main: %._crit_edge*/
/*   %phitmp = add i32 %i.01, 1*/
begin
main___crit_edge_phitmp = (main_17_i_01_reg + 32'd1);
end
end
always @(posedge clk) begin
/* main: %._crit_edge*/
/*   %phitmp = add i32 %i.01, 1*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
main___crit_edge_phitmp_reg <= main___crit_edge_phitmp;
if (^reset !== 1'bX && ^(main___crit_edge_phitmp) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main___crit_edge_phitmp_reg"); $finish; end
end
end
always @(posedge clk) begin
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if (((cur_state == LEGUP_F_main_BB_0_1) & (memory_controller_waitrequest == 1'd0)))
begin
main_1_s_i_0_phi_temp <= main_0_tmp;
if (^reset !== 1'bX && ^(main_0_tmp) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_phi_temp"); $finish; end
end
/* main: %1*/
/*   %s.i.0 = phi i32* [ %tmp, %0 ], [ %6, %4 ]*/
if (((cur_state == LEGUP_F_main_BB_4_3) & (memory_controller_waitrequest == 1'd0)))
begin
main_1_s_i_0_phi_temp <= main_4_6;
if (^reset !== 1'bX && ^(main_4_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_s_i_0_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if (((cur_state == LEGUP_F_main_BB_0_1) & (memory_controller_waitrequest == 1'd0)))
begin
main_1_2_phi_temp <= 32'd2048;
if (^reset !== 1'bX && ^(32'd2048) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_2_phi_temp"); $finish; end
end
/* main: %1*/
/*   %2 = phi i32 [ 2048, %0 ], [ %5, %4 ]*/
if (((cur_state == LEGUP_F_main_BB_4_3) & (memory_controller_waitrequest == 1'd0)))
begin
main_1_2_phi_temp <= main_4_5;
if (^reset !== 1'bX && ^(main_4_5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_1_2_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5) & (memory_controller_waitrequest == 1'd0)))
begin
main_9_s_i2_0_phi_temp <= main_legup_memset_4_exit_tmp1_reg;
if (^reset !== 1'bX && ^(main_legup_memset_4_exit_tmp1_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_phi_temp"); $finish; end
end
/* main: %9*/
/*   %s.i2.0 = phi i32* [ %tmp1, %legup_memset_4.exit ], [ %14, %12 ]*/
if (((cur_state == LEGUP_F_main_BB_12_7) & (memory_controller_waitrequest == 1'd0)))
begin
main_9_s_i2_0_phi_temp <= main_12_14;
if (^reset !== 1'bX && ^(main_12_14) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_s_i2_0_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5) & (memory_controller_waitrequest == 1'd0)))
begin
main_9_10_phi_temp <= 32'd2048;
if (^reset !== 1'bX && ^(32'd2048) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_10_phi_temp"); $finish; end
end
/* main: %9*/
/*   %10 = phi i32 [ 2048, %legup_memset_4.exit ], [ %13, %12 ]*/
if (((cur_state == LEGUP_F_main_BB_12_7) & (memory_controller_waitrequest == 1'd0)))
begin
main_9_10_phi_temp <= main_12_13;
if (^reset !== 1'bX && ^(main_12_13) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_9_10_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %18 = phi i32 [ 4, %legup_memset_4.exit3 ], [ %.pre4, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_18_phi_temp <= 32'd4;
if (^reset !== 1'bX && ^(32'd4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_18_phi_temp"); $finish; end
end
/* main: %17*/
/*   %18 = phi i32 [ 4, %legup_memset_4.exit3 ], [ %.pre4, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_18_phi_temp <= main___crit_edge__pre4;
if (^reset !== 1'bX && ^(main___crit_edge__pre4) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_18_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %19 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %.pre, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_19_phi_temp <= 32'd1;
if (^reset !== 1'bX && ^(32'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_19_phi_temp"); $finish; end
end
/* main: %17*/
/*   %19 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %.pre, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_19_phi_temp <= main___crit_edge__pre;
if (^reset !== 1'bX && ^(main___crit_edge__pre) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_19_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %sum.02 = phi i32 [ 0, %legup_memset_4.exit3 ], [ %21, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_sum_02_phi_temp <= 32'd0;
if (^reset !== 1'bX && ^(32'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_sum_02_phi_temp"); $finish; end
end
/* main: %17*/
/*   %sum.02 = phi i32 [ 0, %legup_memset_4.exit3 ], [ %21, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_sum_02_phi_temp <= main_17_21_reg;
if (^reset !== 1'bX && ^(main_17_21_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_sum_02_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_i_01_phi_temp <= 32'd1;
if (^reset !== 1'bX && ^(32'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_phi_temp"); $finish; end
end
/* main: %17*/
/*   %i.01 = phi i32 [ 1, %legup_memset_4.exit3 ], [ %phitmp, %._crit_edge ]*/
if (((cur_state == LEGUP_F_main_BB___crit_edge_13) & (memory_controller_waitrequest == 1'd0)))
begin
main_17_i_01_phi_temp <= main___crit_edge_phitmp_reg;
if (^reset !== 1'bX && ^(main___crit_edge_phitmp_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_17_i_01_phi_temp"); $finish; end
end
end
always @(posedge clk) begin
if ((cur_state == LEGUP_0))
begin
finish <= 1'd0;
if (^reset !== 1'bX && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
end
/* main: %22*/
/*   ret i32 %21*/
if ((cur_state == LEGUP_F_main_BB_22_14))
begin
finish <= (memory_controller_waitrequest == 1'd0);
if (^reset !== 1'bX && ^((memory_controller_waitrequest == 1'd0)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
end
end
always @(posedge clk) begin
if ((cur_state == LEGUP_0))
begin
return_val <= 0;
if (^reset !== 1'bX && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
end
/* main: %22*/
/*   ret i32 %21*/
if ((cur_state == LEGUP_F_main_BB_22_14))
begin
return_val <= main_17_21_reg;
if (^reset !== 1'bX && ^(main_17_21_reg) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
end
end
always @(*) begin
memory_controller_enable_a = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_enable_a = 1'd0;
end
/* main: %4*/
/*   store i32 0, i32* %s.i.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_4_3))
begin
memory_controller_enable_a = 1'd1;
end
/* main: %legup_memset_4.exit*/
/*   store i32 1, i32* %tmp, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_enable_a = 1'd1;
end
/* main: %12*/
/*   store i32 0, i32* %s.i2.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_12_7))
begin
memory_controller_enable_a = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 4, i32* %tmp1, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_enable_a = 1'd1;
end
/* main: %._crit_edge*/
/*   %.pre = load i32* %scevgep.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_enable_a = 1'd1;
end
end
always @(*) begin
memory_controller_address_a = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_address_a = 0;
end
/* main: %4*/
/*   store i32 0, i32* %s.i.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_4_3))
begin
memory_controller_address_a = main_1_s_i_0_reg;
end
/* main: %legup_memset_4.exit*/
/*   store i32 1, i32* %tmp, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_address_a = main_0_tmp_reg;
end
/* main: %12*/
/*   store i32 0, i32* %s.i2.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_12_7))
begin
memory_controller_address_a = main_9_s_i2_0_reg;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 4, i32* %tmp1, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_address_a = main_legup_memset_4_exit_tmp1_reg;
end
/* main: %._crit_edge*/
/*   %.pre = load i32* %scevgep.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_address_a = main___crit_edge_scevgep_phi_trans_insert;
end
end
always @(*) begin
memory_controller_write_enable_a = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_write_enable_a = 1'd0;
end
/* main: %4*/
/*   store i32 0, i32* %s.i.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_4_3))
begin
memory_controller_write_enable_a = 1'd1;
end
/* main: %legup_memset_4.exit*/
/*   store i32 1, i32* %tmp, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_write_enable_a = 1'd1;
end
/* main: %12*/
/*   store i32 0, i32* %s.i2.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_12_7))
begin
memory_controller_write_enable_a = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 4, i32* %tmp1, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_write_enable_a = 1'd1;
end
/* main: %._crit_edge*/
/*   %.pre = load i32* %scevgep.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_write_enable_a = 1'd0;
end
end
always @(*) begin
memory_controller_in_a = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_in_a = 64'd0;
end
/* main: %4*/
/*   store i32 0, i32* %s.i.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_4_3))
begin
memory_controller_in_a = 32'd0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 1, i32* %tmp, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_in_a = 32'd1;
end
/* main: %12*/
/*   store i32 0, i32* %s.i2.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_12_7))
begin
memory_controller_in_a = 32'd0;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 4, i32* %tmp1, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_in_a = 32'd4;
end
end
always @(*) begin
memory_controller_size_a = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_size_a = 2'd0;
end
/* main: %4*/
/*   store i32 0, i32* %s.i.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_4_3))
begin
memory_controller_size_a = 2'd2;
end
/* main: %legup_memset_4.exit*/
/*   store i32 1, i32* %tmp, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_size_a = 2'd2;
end
/* main: %12*/
/*   store i32 0, i32* %s.i2.0, align 4*/
if ((cur_state == LEGUP_F_main_BB_12_7))
begin
memory_controller_size_a = 2'd2;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 4, i32* %tmp1, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_size_a = 2'd2;
end
/* main: %._crit_edge*/
/*   %.pre = load i32* %scevgep.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_size_a = 2'd2;
end
end
always @(*) begin
memory_controller_enable_b = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_enable_b = 1'd0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 2, i32* %7, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit*/
/*   store i32 3, i32* %8, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5))
begin
memory_controller_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 5, i32* %15, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 6, i32* %16, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9))
begin
memory_controller_enable_b = 1'd1;
end
/* main: %._crit_edge*/
/*   %.pre4 = load i32* %scevgep3.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_enable_b = 1'd1;
end
end
always @(*) begin
memory_controller_address_b = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_address_b = 0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 2, i32* %7, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_address_b = main_legup_memset_4_exit_7;
end
/* main: %legup_memset_4.exit*/
/*   store i32 3, i32* %8, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5))
begin
memory_controller_address_b = main_legup_memset_4_exit_8_reg;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 5, i32* %15, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_address_b = main_legup_memset_4_exit3_15;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 6, i32* %16, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9))
begin
memory_controller_address_b = main_legup_memset_4_exit3_16_reg;
end
/* main: %._crit_edge*/
/*   %.pre4 = load i32* %scevgep3.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_address_b = main___crit_edge_scevgep3_phi_trans_insert;
end
end
always @(*) begin
memory_controller_write_enable_b = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_write_enable_b = 1'd0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 2, i32* %7, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_write_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit*/
/*   store i32 3, i32* %8, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5))
begin
memory_controller_write_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 5, i32* %15, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_write_enable_b = 1'd1;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 6, i32* %16, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9))
begin
memory_controller_write_enable_b = 1'd1;
end
/* main: %._crit_edge*/
/*   %.pre4 = load i32* %scevgep3.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_write_enable_b = 1'd0;
end
end
always @(*) begin
memory_controller_in_b = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_in_b = 64'd0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 2, i32* %7, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_in_b = 32'd2;
end
/* main: %legup_memset_4.exit*/
/*   store i32 3, i32* %8, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5))
begin
memory_controller_in_b = 32'd3;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 5, i32* %15, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_in_b = 32'd5;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 6, i32* %16, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9))
begin
memory_controller_in_b = 32'd6;
end
end
always @(*) begin
memory_controller_size_b = 1'd0;
if ((cur_state == LEGUP_0))
begin
memory_controller_size_b = 2'd0;
end
/* main: %legup_memset_4.exit*/
/*   store i32 2, i32* %7, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_4))
begin
memory_controller_size_b = 2'd2;
end
/* main: %legup_memset_4.exit*/
/*   store i32 3, i32* %8, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit_5))
begin
memory_controller_size_b = 2'd2;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 5, i32* %15, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_8))
begin
memory_controller_size_b = 2'd2;
end
/* main: %legup_memset_4.exit3*/
/*   store i32 6, i32* %16, align 4*/
if ((cur_state == LEGUP_F_main_BB_legup_memset_4_exit3_9))
begin
memory_controller_size_b = 2'd2;
end
/* main: %._crit_edge*/
/*   %.pre4 = load i32* %scevgep3.phi.trans.insert, align 4, !tbaa !0*/
if ((cur_state == LEGUP_F_main_BB___crit_edge_11))
begin
memory_controller_size_b = 2'd2;
end
end

endmodule 
`timescale 1 ns / 1 ns
module ram_dual_port
(
	clk,
	address_a,
	address_b,
	wren_a,
	wren_b,
	data_a,
	data_b,
	q_a,
	q_b,
	byteena_a,
	byteena_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED";
parameter  width_be_a = 1'd0;
parameter  width_be_b = 1'd0;

input  clk;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
input  wren_a;
input  wren_b;
input [(width_a-1):0] data_a;
input [(width_b-1):0] data_b;
output [(width_a-1):0] q_a;
output [(width_b-1):0] q_b;
input [width_be_a-1:0] byteena_a;
input [width_be_b-1:0] byteena_b;
reg  clk_wire;


altsyncram altsyncram_component (
	.clock0 (clk_wire),
	.clock1 (1'd1),
	.clocken0 (1'd1),
	.clocken1 (1'd1),
	.clocken2 (1'd1),
	.clocken3 (1'd1),
	.aclr0 (1'd0),
	.aclr1 (1'd0),
	.addressstall_a (1'd0),
	.addressstall_b (1'd0),
	.eccstatus (),
	.address_a (address_a),
	.address_b (address_b),
	.wren_a (wren_a),
	.wren_b (wren_b),
	.rden_a (1'd1),
	.rden_b (1'd1),
	.data_a (data_a),
	.data_b (data_b),
	.q_a (q_a),
	.q_b (q_b),
	.byteena_a (byteena_a),
	.byteena_b (byteena_b)
);

defparam
	altsyncram_component.operation_mode = "BIDIR_DUAL_PORT",
	altsyncram_component.read_during_write_mode_mixed_ports = "OLD_DATA",
	altsyncram_component.init_file = init_file,
	altsyncram_component.lpm_hint = "ENABLE_RUNTIME_MOD=NO",
	altsyncram_component.lpm_type = "altsyncram",
	altsyncram_component.power_up_uninitialized = "FALSE",
	altsyncram_component.intended_device_family = "Cyclone II",
	altsyncram_component.clock_enable_input_a = "BYPASS",
	altsyncram_component.clock_enable_input_b = "BYPASS",
	altsyncram_component.clock_enable_output_a = "BYPASS",
	altsyncram_component.clock_enable_output_b = "BYPASS",
	altsyncram_component.outdata_aclr_a = "NONE",
	altsyncram_component.outdata_aclr_b = "NONE",
	altsyncram_component.outdata_reg_a = "UNREGISTERED",
	altsyncram_component.outdata_reg_b = "UNREGISTERED",
	altsyncram_component.numwords_a = numwords_a,
	altsyncram_component.numwords_b = numwords_b,
	altsyncram_component.widthad_a = widthad_a,
	altsyncram_component.widthad_b = widthad_b,
	altsyncram_component.width_a = width_a,
	altsyncram_component.width_b = width_b,
	altsyncram_component.address_reg_b = "CLOCK0",
	altsyncram_component.byteena_reg_b = "CLOCK0",
	altsyncram_component.indata_reg_b = "CLOCK0",
	altsyncram_component.wrcontrol_wraddress_reg_b = "CLOCK0",
	altsyncram_component.width_byteena_a = width_be_a,
	altsyncram_component.width_byteena_b = width_be_b;


always @(*) begin
clk_wire = clk;
end

endmodule 
module de2 (CLOCK_50, KEY, SW, HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, HEX6, HEX7, LEDG);
    input CLOCK_50;
    output [7:0] LEDG;
    input [1:0] KEY;
    input [15:0] SW;
    output [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, HEX6, HEX7;

    wire  clk;
    wire reset = ~KEY[0];
    wire go = ~KEY[1];

    wire  start;
    wire [31:0] return_val;
    wire  finish;

    reg [31:0] return_val_reg;
    
    hex_digits h7( .x(return_val_reg[31:28]), .hex_LEDs(HEX7));
    hex_digits h6( .x(return_val_reg[27:24]), .hex_LEDs(HEX6));
    hex_digits h5( .x(return_val_reg[23:20]), .hex_LEDs(HEX5));
    hex_digits h4( .x(return_val_reg[19:16]), .hex_LEDs(HEX4));
    hex_digits h3( .x(return_val_reg[15:12]), .hex_LEDs(HEX3));
    hex_digits h2( .x(return_val_reg[11:8]), .hex_LEDs(HEX2));
    hex_digits h1( .x(return_val_reg[7:4]), .hex_LEDs(HEX1));
    hex_digits h0( .x(return_val_reg[3:0]), .hex_LEDs(HEX0));


    top top_inst (
        .clk (clk),
        .reset (reset),
        .start (start),
        .finish (finish),
        .return_val (return_val)
    );

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);
endmodule

module de4 (
	OSC_50_BANK2,
    BUTTON,
    LED,
	SEG0_D,
	SEG1_D
);
    input OSC_50_BANK2;
    input [1:0] BUTTON;
    output [6:0] SEG0_D;
    output [6:0] SEG1_D;
    output [7:0] LED;

    de2 de2_inst (
        .CLOCK_50 (OSC_50_BANK2),
        .LEDG (LED),
        .KEY (BUTTON),
        .SW (),
        .HEX0 (SEG0_D),
        .HEX1 (SEG1_D),
        .HEX2 (),
        .HEX3 (),
        .HEX4 (),
        .HEX5 (),
        .HEX6 (),
        .HEX7 ()
    );

endmodule
module hex_digits(x, hex_LEDs);
    input [3:0] x;
    output [6:0] hex_LEDs;
    
    assign hex_LEDs[0] = (~x[3] & ~x[2] & ~x[1] & x[0]) |
                            (~x[3] & x[2] & ~x[1] & ~x[0]) |
                            (x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & ~x[2] & x[1] & x[0]);
    assign hex_LEDs[1] = (~x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & x[1] & x[0]) |
                            (x[3] & x[2] & ~x[0]) |
                            (x[2] & x[1] & ~x[0]);
    assign hex_LEDs[2] = (x[3] & x[2] & ~x[0]) |
                            (x[3] & x[2] & x[1]) |
                            (~x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[3] = (~x[3] & ~x[2] & ~x[1] & x[0]) | 
                            (~x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (x[2] & x[1] & x[0]) | 
                            (x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[4] = (~x[3] & x[0]) |
                            (~x[3] & x[2] & ~x[1]) |
                            (~x[2] & ~x[1] & x[0]);
    assign hex_LEDs[5] = (~x[3] & ~x[2] & x[0]) | 
                            (~x[3] & ~x[2] & x[1]) | 
                            (~x[3] & x[1] & x[0]) | 
                            (x[3] & x[2] & ~x[1] & x[0]);
    assign hex_LEDs[6] = (~x[3] & ~x[2] & ~x[1]) | 
                            (x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (~x[3] & x[2] & x[1] & x[0]);
    
endmodule
`timescale 1 ns / 1 ns
module main_tb
(
);

reg  clk;
reg  reset;
reg  start;
wire [31:0] return_val;
wire  finish;


top top_inst (
	.clk (clk),
	.reset (reset),
	.start (start),
	.finish (finish),
	.return_val (return_val)
);




initial 
    clk = 0;
always @(clk)
    clk <= #10 ~clk;

initial begin
//$monitor("At t=%t clk=%b %b %b %b %d", $time, clk, reset, start, finish, return_val);
@(negedge clk);
reset <= 1;
@(negedge clk);
reset <= 0;
start <= 1;

end

always@(finish) begin
    if (finish == 1) begin
        $display("At t=%t clk=%b finish=%b return_val=%d", $time, clk, finish, return_val);
        $display("Cycles: %d", ($time-50)/20);
        $finish;
    end
end

endmodule 
