#!/bin/bash

# for OSX
function my_readlinkdir() {
	local FILE="$1"
	if [ -L "$FILE" ]; then
		local LINK="$(readlink -- "$FILE")"
		cd -- "$(dirname -- "$FILE")"
		cd -- "$(dirname -- "$LINK")"
	else
		cd -- "$(dirname -- "$FILE")"
	fi
	pwd
}
function my_pdirname() {
	cd -- "$1/.."
	pwd
}

LALP_COMMAND="$(basename -- "$0")"
if [ -n "$LALP_HOME" ]; then
	LALP_BIN="$LALP_HOME/bin"
else
	LALP_BIN="$(my_readlinkdir "$0")"
	LALP_HOME="$(my_pdirname "$LALP_BIN")"
fi

LALP_LIBS="$LALP_HOME/lib"

LALP_JAR_JUNG="$LALP_LIBS/jung-1.7.6.jar"
LALP_JAR_COLT="$LALP_LIBS/colt.jar"
LALP_JAR_COMMONS_COLLECTIONS="$LALP_LIBS/commons-collections-3.2.jar"

if [[ "$(uname -s)" =~ ^CYGWIN ]]; then
	SEP=";"
else
	SEP=":"
fi

LALP_CP_TOOL="$LALP_JAR_JUNG$SEP$LALP_JAR_COLT$SEP$LALP_JAR_COMMONS_COLLECTIONS$SEP$LALP_HOME/bin"

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LALP_BIN"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$LALP_BIN"

java -DLALP.home="$LALP_HOME" -DCOMMAND_NAME="$LALP_COMMAND" -Djava.library.path="$LALP_BIN" -classpath "$LALP_CP_TOOL" lalp.LALP "$@"
