#! /bin/csh -f
#

#ghdl -a --work=ieee_proposed math_real.vhdl
#ghdl -a --work=ieee_proposed math_real-body.vhdl
#ghdl -a --work=ieee_proposed math_complex.vhdl
#ghdl -a --work=ieee_proposed math_complex-body.vhdl
ghdl -a --work=ieee_proposed math_real_fmod.vhdl
ghdl -a --work=ieee_proposed standard_additions_c.vhdl
ghdl -a --work=ieee_proposed standard_textio_additions_c.vhdl
ghdl -a --work=ieee_proposed env_c.vhdl
ghdl -a --work=ieee_proposed std_logic_1164_additions.vhdl
ghdl -a --work=ieee_proposed numeric_std_additions.vhdl
ghdl -a --work=ieee_proposed numeric_std_unsigned_c.vhdl
ghdl -a --work=ieee_proposed fixed_float_types_c.vhdl
ghdl -a --work=ieee_proposed fixed_pkg_c.vhdl
ghdl -a --work=ieee_proposed float_pkg_c.vhdl


