/* Generated By:JavaCC: Do not edit this line. JavaParserTreeConstants.java Version 4.2 */
package alp.parser.lang.java;

public interface JavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTTYPEDECLARATION = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTCLASSBODYDECLARATION = 5;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 6;
  public int JJTINTERFACEDECLARATION = 7;
  public int JJTINTERFACEMEMBERDECLARATION = 8;
  public int JJTFIELDDECLARATION = 9;
  public int JJTVARIABLEDECLARATOR = 10;
  public int JJTVARIABLEDECLARATORID = 11;
  public int JJTVARIABLEINITIALIZER = 12;
  public int JJTMETHODDECLARATION = 13;
  public int JJTMETHODDECLARATOR = 14;
  public int JJTFORMALPARAMETERS = 15;
  public int JJTFORMALPARAMETER = 16;
  public int JJTCONSTRUCTORDECLARATION = 17;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 18;
  public int JJTSTATICINITIALIZER = 19;
  public int JJTTYPE = 20;
  public int JJTPRIMITIVETYPE = 21;
  public int JJTRESULTTYPE = 22;
  public int JJTNAME = 23;
  public int JJTNAMELIST = 24;
  public int JJTEXPRESSION = 25;
  public int JJTASSIGNMENT = 26;
  public int JJTASSIGNMENTOPERATOR = 27;
  public int JJTCONDITIONALEXPRESSION = 28;
  public int JJTCONDITIONALOREXPRESSION = 29;
  public int JJTCONDITIONALANDEXPRESSION = 30;
  public int JJTINCLUSIVEOREXPRESSION = 31;
  public int JJTEXCLUSIVEOREXPRESSION = 32;
  public int JJTANDEXPRESSION = 33;
  public int JJTEQUALITYEXPRESSION = 34;
  public int JJTINSTANCEOFEXPRESSION = 35;
  public int JJTRELATIONALEXPRESSION = 36;
  public int JJTSHIFTEXPRESSION = 37;
  public int JJTADDITIVEEXPRESSION = 38;
  public int JJTMULTIPLICATIVEEXPRESSION = 39;
  public int JJTUNARYEXPRESSION = 40;
  public int JJTPREINCREMENTEXPRESSION = 41;
  public int JJTPREDECREMENTEXPRESSION = 42;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 43;
  public int JJTCASTLOOKAHEAD = 44;
  public int JJTPOSTFIXEXPRESSION = 45;
  public int JJTCASTEXPRESSION = 46;
  public int JJTPRIMARYEXPRESSION = 47;
  public int JJTPRIMARYPREFIX = 48;
  public int JJTPRIMARYSUFFIX = 49;
  public int JJTLITERAL = 50;
  public int JJTBOOLEANLITERAL = 51;
  public int JJTNULLLITERAL = 52;
  public int JJTARGUMENTS = 53;
  public int JJTARGUMENTLIST = 54;
  public int JJTALLOCATIONEXPRESSION = 55;
  public int JJTARRAYDIMENSIONS = 56;
  public int JJTSTATEMENT = 57;
  public int JJTLABELEDSTATEMENT = 58;
  public int JJTBLOCK = 59;
  public int JJTBLOCKSTATEMENT = 60;
  public int JJTLOCALVARIABLEDECLARATION = 61;
  public int JJTEMPTYSTATEMENT = 62;
  public int JJTSTATEMENTEXPRESSION = 63;
  public int JJTSWITCHSTATEMENT = 64;
  public int JJTSWITCHLABEL = 65;
  public int JJTIFSTATEMENT = 66;
  public int JJTWHILESTATEMENT = 67;
  public int JJTDOSTATEMENT = 68;
  public int JJTFORSTATEMENT = 69;
  public int JJTFORINIT = 70;
  public int JJTSTATEMENTEXPRESSIONLIST = 71;
  public int JJTFORUPDATE = 72;
  public int JJTBREAKSTATEMENT = 73;
  public int JJTCONTINUESTATEMENT = 74;
  public int JJTRETURNSTATEMENT = 75;
  public int JJTTHROWSTATEMENT = 76;
  public int JJTSYNCHRONIZEDSTATEMENT = 77;
  public int JJTTRYSTATEMENT = 78;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "TypeDeclaration",
    "ClassDeclaration",
    "ClassBodyDeclaration",
    "MethodDeclarationLookahead",
    "InterfaceDeclaration",
    "InterfaceMemberDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "StaticInitializer",
    "Type",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "Assignment",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimensions",
    "Statement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
  };
}
/* JavaCC - OriginalChecksum=bdcf96f23a12761722071b2dd1d20f57 (do not edit this line) */
