/* Generated By:JavaCC: Do not edit this line. ALPParserTreeConstants.java Version 5.0 */
package lalp.parser.lang;

public interface ALPParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTTESTBENCH = 1;
  public int JJTRESULTS = 2;
  public int JJTNAME = 3;
  public int JJTCONST = 4;
  public int JJTTYPEDEF = 5;
  public int JJTVOID = 6;
  public int JJTPIN = 7;
  public int JJTVARIABLE = 8;
  public int JJTRESULT = 9;
  public int JJTCOUNTER = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTWHEN = 12;
  public int JJTLHS = 13;
  public int JJTRHS = 14;
  public int JJTEXPRESSION = 15;
  public int JJTDELAYEXPRESSION = 16;
  public int JJTCONDITIONALEXPRESSION = 17;
  public int JJTCONDITIONALOREXPRESSION = 18;
  public int JJTCONDITIONALANDEXPRESSION = 19;
  public int JJTINCLUSIVEOREXPRESSION = 20;
  public int JJTEXCLUSIVEOREXPRESSION = 21;
  public int JJTANDEXPRESSION = 22;
  public int JJTEQUALITYEXPRESSION = 23;
  public int JJTRELATIONALEXPRESSION = 24;
  public int JJTSHIFTEXPRESSION = 25;
  public int JJTADDITIVEEXPRESSION = 26;
  public int JJTMULTIPLICATIVEEXPRESSION = 27;
  public int JJTUNARYEXPRESSION = 28;
  public int JJTPREINCREMENTEXPRESSION = 29;
  public int JJTPREDECREMENTEXPRESSION = 30;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 31;
  public int JJTPOSTFIXEXPRESSION = 32;
  public int JJTPRIMARYEXPRESSION = 33;
  public int JJTLITERAL = 34;


  public String[] jjtNodeName = {
    "Start",
    "Testbench",
    "Results",
    "Name",
    "Const",
    "Typedef",
    "void",
    "Pin",
    "Variable",
    "Result",
    "Counter",
    "Assignment",
    "When",
    "LHS",
    "RHS",
    "Expression",
    "DelayExpression",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "PostfixExpression",
    "PrimaryExpression",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=3bafcbe5a1c0b7936d0874aa7026470c (do not edit this line) */
